name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++

    - name: Build
      run: g++ -o myapp main.cpp

    - name: Archive the build
      uses: actions/upload-artifact@v2
      with:
        name: DivisibleBy5
        path: build/main
